### ISSUE TITLE
how to resolve colliding with rectangle which has rotation

### ISSUE THREAD

**Issue by tuanna222** [gameclosure/devkit-entities#1]
Please help me. I can not resolve colliding with rectangular entity which has rotating animation on its view.
Ex: 

var Bullet = Class(Entity, function() {
    var sup = Entity.prototype;

```
this.name = "Bullet";

this.init = function(opts) {
    sup.init.call(this, opts);
};
```

this.update = function(dt) {
        sup.init.call(this, dt);
        animate(this.view).now({dr: Math.PI / 5});
    };});

**Comment by rogueSkib** [comment]
Unfortunately Entity doesn't support rotated rectangles, yet.

If you modify the collision functions in [EntityPhysics](https://github.com/gameclosure/devkit-entities/blob/master/src/EntityPhysics.js) to support rotated rectangles, I'd be happy to review and merge pull requests! You could use the `r` property on [hit bounds objects](https://github.com/gameclosure/devkit-entities/blob/master/src/Entity.js#L353) to get started.

**Comment by tuanna222** [comment]
I applied SAT.js to this plugin to support rotation on Circle and Rectangle. Please refer to: 
https://github.com/tuanna222/devkit-entities/tree/v0.3.0

**Comment by rogueSkib** [comment]
Hey, that's really cool! SAT.js looks like a very useful physics library for complex polygon collisions! Thanks for sharing your fork :)

Are you interested in merging it back on our main line eventually? If so, I'd want to keep some of the original functionality that got deleted, like `resolveCollidingStateWith`, and apply SAT.js as an [alternative physics class](https://github.com/gameclosure/devkit-entities/blob/master/src/Entity.js#L103). I like the defaults as a lightweight and minimal implementation: ideal for simple bullet-hell type games with tons and tons of entities active simultaneously. I wonder if SAT.js would add significant overhead to such a game? I might end up writing a performance test using [gcPerf](https://github.com/gameclosure/gcPerf) to find out. If it was negligible at high volume, then it might make more sense to make SAT.js the default. Let me know what you think!

**Comment by tuanna222** [comment]
I've changed code to support switching between SATPhysics and EntityPhysics. Default is EntityPhysics.
https://github.com/tuanna222/devkit-entities/tree/v0.3.1

**Comment by tuanna222** [comment]
Bug Fixed: https://github.com/tuanna222/devkit-entities/tree/v0.3.3
- Release SAT physics when releasing Entity
- Restore deleted Entity pieces to support EntityPhysics
