### ISSUE TITLE
debugDraw is super broken

### ISSUE THREAD

**Issue by yofreke** [gameclosure/devkit-entities#8]
Needs to be further up the call stack so that it doesnt have to undo all the view style drawing

**Comment by rogueSkib** [comment]
I've been using it on the latest `master` without issue so far, any ideas on what is breaking it for you? Maybe a style property we forgot to account for?

Having it happen earlier, before Views modify the canvas context, would need for devkit to know about entity's shapes. Did you have anything in mind to resolve this?

**Comment by rogueSkib** [comment]
Pushed a fix to `master`, `showHitBounds` properly accounts for view style props `scale`, `anchorX`, and `anchorY`. Re-open or create a new issue if you find anything else!
